name: env_snap
channels:
  - terradue
  - conda-forge
dependencies:
  - snap
  - ipykernel
  - jupyter_client
  - pip
  - pip: 
    - rasterio
    - sentinelsat
    - nteract-scrapbook
    - papermill
    - folium 
    - shapely
    - matplotlib
    - scikit-image
